name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    name: Package Chrome and Safari builds
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build Chrome and Safari
        run: npm run build

      - name: Package Safari Xcode project
        run: |
          tar -czf dist/safari/pdp-rewriter-safari-project.tgz -C dist/safari "PDP Rewriter"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/chrome/pdp-rewriter-extension.zip
            dist/safari/pdp-rewriter-safari-project.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


